name: Build alien
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    secrets: inherit
    with:
      VERSION: "feature/slack-desc-handling-pending-test"
      NAME: "alien"
      SOURCE: https://github.com/bobbintb/alien.git
