name: Build alien
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    secrets: inherit
    with:
      VERSION: "8.96"
      NAME: "alien"
      GIT: https://github.com/bobbintb/alien.git
