name: -Build bcc
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    secrets: inherit
    with:
      bobbintb: true
      VERSION: "0.33.0"
      NAME: "bcc"
      SBOPKG: true
      #PACKAGES: "cmake make llvm guile"
      PACKAGES: "llvm ccache libssh2 libedit fmt cmake make guile gc binutils gcc kernel-headers bobbintb:libbpf"
      PIP: setuptools
      SOURCE: https://github.com/iovisor/bcc.git
