name: Build bcc
on:
  workflow_dispatch:
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    with:
      VERSION: "0.32.0"
      NAME: "bcc"
      UPGRADE-ALL: true
      PACKAGES: "llvm ccache libssh2"
      SOURCE: "https://github.com/iovisor/bcc/releases/download/v0.32.0/bcc-src-with-submodule.tar.gz"
