name: Build bcc
on:
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/sbopkg_template.yml@main
    secrets: inherit
    with:
      NAME: "bcc"
      PACKAGES: "ccache gettext lua luajit fmt python-setuptools"
      REINSTALL: libedit
      UPGRADE: "libxml2 xz zlib elfutils && wget 'https://slackware.uk/cumulative/slackware64-current/slackware64/d/llvm-17.0.6-x86_64-1.txz' && installpkg llvm-17.0.6-x86_64-1.txz"
      GIT: "https://github.com/iovisor/bcc.git"
