name: Build bcc
on:
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/sbopkg_template.yml@main
    secrets: inherit
    with:
      NAME: "bcc"
      PACKAGES: "ccache gettext lua luajit fmt"
      REINSTALL: libedit
      UPGRADE: "libxml2 xz zlib elfutils"
      GIT: "https://github.com/iovisor/bcc.git"
