name: Build bitwarden-cli
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    secrets: inherit
    with:
      VERSION: "2025.3.0"
      NAME: "bitwarden-cli"
