name: -Build bpftrace
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    secrets: inherit
    with:
      VERSION: "0.22.1"
      NAME: "bpftrace"
      SBOPKG: true
      bobbintb: true
      alien-15: true
      PACKAGES: "make cmake cc gcc guile gc binutils bcc libbpf cereal bison gettext llvm vim pahole gtest asciidoctor m4 ccache fmt kernel-headers ruby"
      # PACKAGES: "libedit libssh2 ruby nghttp3"
      PIP: setuptools

# name: Build bpftrace
# on:
#   workflow_dispatch:
# env:
#   VERSION: "0.21.3"
#   NAME: "bpftrace"
# jobs:
#   slackware-job:
#     permissions: write-all
#     runs-on: ubuntu-latest
#     container:
#       image: spaceinvaderone/auto_slack_pack
#       options: --privileged
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v4
#     - name: Update and install packages
#       run: |
#         echo "================================= Updating packages ================================="
#         CONF_FILE="/etc/slackpkg/slackpkg.conf"
#         sed -i "s/^DIALOG=.*/DIALOG=off/" "$CONF_FILE"
#         sed -i "s/^BATCH=.*/BATCH=on/" "$CONF_FILE"
#         sed -i "s/^DEFAULT_ANSWER=.*/DEFAULT_ANSWER=y/" "$CONF_FILE"
#         sed -i '$s/.*/https:\/\/mirrors\.slackware\.com\/slackware\/slackware64-current\//' /etc/slackpkg/mirrors
#         slackpkg update gpg <<< y
#         slackpkg update <<< y
#         #slackpkg upgrade-all
#         ##############################################
#         slackpkg install ccache vim asciidoctor libedit libssh2 ruby nghttp3 llvm fmt 
#         slackpkg upgrade-all || true
#         slackpkg upgrade-all || true
#         slackpkg upgrade-all || true
#         slackpkg upgrade-all || true
#         ##############################################
#         # wget https://slackware.uk/slackware/slackware64-current/slackware64/d/luajit-2.1.1732813678-x86_64-1.txz
#         wget https://slackware.uk/slackware/slackware64-15.0/slackware64/d/llvm-13.0.0-x86_64-2.txz
#         wget https://github.com/bobbintb/Slackware_Packages/raw/refs/heads/main/libbpf/libbpf-1.5.0-x86_64-1cf.txz
#         wget https://github.com/bobbintb/Slackware_Packages/raw/refs/heads/main/bcc/bcc-0.32.0-x86_64-1_SBo.tgz
#         wget https://slackware.uk/people/alien/sbrepos/current/x86_64/cereal/cereal-1.3.0-x86_64-1alien.txz
#         wget https://slackware.uk/slackware/slackware64-current/slackware64/d/pahole-1.28-x86_64-1.txz
#         wget https://ftp.sotirov-bg.net/pub/contrib/slackware/packages/slackware64-15.0/gtest-1.11.0-x86_64-2gds.txz
#         ##############################################
#         installpkg *.txz
#         rm *.txz
#         installpkg *.tgz
#         rm *.tgz
#     - name: Build
#       run: |
#         echo "================================= Downloading source code ================================="
#         REPO=${GITHUB_REPOSITORY##*/}
#         REPO_DIR="/__w/${REPO}/${REPO}"
#         mkdir -p ${REPO_DIR}/${NAME}
#         cd ./SlackBuilds/$NAME
#         ##############################################
#         wget https://github.com/iovisor/${NAME}/archive/refs/tags/v${VERSION}/${NAME}-${VERSION}.tar.gz
#         find / -name "LLVMConfig.cmake" 2>/dev/null
#         # /usr/lib64/cmake/llvm/
#         # export LLVM_DIR=/tmp/llvm-13.0.0.src/build/lib64/cmake/llvm/
#         ##############################################
#         sh ${REPO_DIR}/SlackBuilds/${NAME}/${NAME}.SlackBuild
#         git config --global --add safe.directory $REPO_DIR
#         cp /tmp/*.tgz ${REPO_DIR}/${NAME}
#     - name: Commit changes
#       uses: stefanzweifel/git-auto-commit-action@v5
#       with:
#         commit_message: 'updated ${{ env.NAME }}'
#         file_pattern: '*.tgz'
