name: Build bpftrace
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    secrets: inherit
    with:
      VERSION: "0.23.2"
      NAME: "bpftrace"
      SBOPKG: true
      bobbintb: true
      alien-15: true
      PACKAGES: "make cmake cc gcc guile gc binutils bcc libbpf cereal bison gettext llvm vim pahole gtest asciidoctor m4 ccache fmt kernel-headers ruby"
      PIP: setuptools
