name: Build bpftrace
on:
  workflow_dispatch:
    inputs:
      do_deploy:
        description: 'Deploy to GitHub Pages?'
        required: false
        type: boolean
        default: true
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/sbopkg_template.yml@main
    secrets: inherit
    with:
      DEPLOY: ${{ inputs.do_deploy }}
      NAME: "bpftrace"
      # PACKAGES: "bcc cereal gettext vim bpftool pahole gtest m4 ccache fmt ruby-4 rubygem-asciidoctor"
      # UPGRADE: "zlib elfutils libxml2 libpcap"
      # REINSTALL: "libedit"
      # REPOS: "bobbintb SlackDCE_Project-15.0"
      # GIT: "https://github.com/bpftrace/bpftrace.git"
      BINARY_URL: "https://github.com/bpftrace/bpftrace/releases/download/v0.25.1/bpftrace"
