name: Build bpftrace
on:
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/sbopkg_template.yml@main
    secrets: inherit
    with:
      NAME: "bpftrace"
      PACKAGES: "bcc cereal gettext vim bpftool pahole gtest m4 ccache fmt"
      UPGRADE: "zlib elfutils libxml2 libpcap"
      REINSTALL: "libedit"
      REPOS: "bobbintb SlackDCE_Project-15.0"
