name: Build bpftrace
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/binary_template.yml@main
    secrets: inherit
    with:
      NAME: "bpftrace"
      OWNER: "bpftrace"
      REPO: "bpftrace"
      BINARY: "https://github.com/bpftrace/bpftrace/releases/latest/download/bpftrace"
      extra_prep: |
        echo "test"
        echo "test2"
