name: -Build daemonize
on:
  workflow_dispatch:
env:
  VERSION: "1.7.8"
  NAME: "daemonize"
  
jobs:
  slackware-job:
    permissions: write-all
    runs-on: ubuntu-latest
    container: spaceinvaderone/auto_slack_pack
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Update and install packages
      run: |
        echo "================================= Updating packages ================================="
        CONF_FILE="/etc/slackpkg/slackpkg.conf"
        sed -i "s/^DIALOG=.*/DIALOG=off/" "$CONF_FILE"
        sed -i "s/^BATCH=.*/BATCH=on/" "$CONF_FILE"
        sed -i "s/^DEFAULT_ANSWER=.*/DEFAULT_ANSWER=y/" "$CONF_FILE"
        slackpkg update <<< y
    - name: Build
      run: |
        echo "================================= Downloading source code ================================="
        URL="https://github.com/bmc/daemonize/archive/refs/tags/release-${VERSION}.tar.gz"
        REPO=${GITHUB_REPOSITORY##*/}
        REPO_DIR="/__w/${REPO}/${REPO}"
        mkdir -p ${REPO_DIR}/${NAME}
        cd ./SlackBuilds/$NAME
        wget $URL
        mv release-${VERSION}.tar.gz ${NAME}-${VERSION}.tar.gz
        sh ${REPO_DIR}/SlackBuilds/${NAME}/${NAME}.SlackBuild
        git config --global --add safe.directory $REPO_DIR
        cp /tmp/*.tgz ${REPO_DIR}/${NAME}
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'updated ${{ env.NAME }}'
        file_pattern: '*.tgz'
