name: Build dirt
on:
  workflow_dispatch:
    inputs:
      do_deploy:
        description: 'Deploy to GitHub Pages?'
        required: false
        type: boolean
        default: true
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/sbopkg_template.yml@main
    secrets: inherit
    with:
      DEPLOY: ${{ inputs.do_deploy }}
      NAME: "dirt"
      PACKAGES: 'gcc binutils pkgconf kernel-headers bcc bpftrace libbpf llvm && slackpkg remove openssl && slackpkg install openssl && curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && . $HOME/.cargo/env && rustup install stable && rustup toolchain install nightly --component rust-src && cargo install bpf-linker && cargo install cargo-generate && cargo install bindgen-cli && cargo install --git https://github.com/aya-rs/aya -- aya-tool && echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"'
      REPOS: "bobbintb"
      GIT: https://github.com/bobbintb/dirt.git
