name: Build dirt
on:
  workflow_dispatch:
    inputs:
      do_deploy:
        description: 'Deploy to GitHub Pages?'
        required: false
        type: boolean
        default: true
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/sbopkg_template.yml@main
    secrets: inherit
    with:
      DEPLOY: ${{ inputs.do_deploy }}
      VERSION: 0.0.1
      NAME: "dirt"
      PACKAGES: "libbpf"
      REPOS: "bobbintb"
      GIT: https://github.com/bobbintb/dirt.git
