name: Build dotnet-sdk-6.0
on:
  workflow_dispatch:
env:
  VERSION: "6.0"
  NAME: "dotnet-sdk-6.0"
  PACKAGES: ""
  SOURCE: https://download.visualstudio.microsoft.com/download/pr/35b1b4d1-b8f4-4b5c-9ddf-e64a846ee50b/93cc198f1c48fe5c4853bd937226f570/dotnet-sdk-6.0.428-linux-x64.tar.gz
jobs:
  slackware-job:
    permissions: write-all
    runs-on: ubuntu-latest
    container:
      image: spaceinvaderone/auto_slack_pack
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cache packages
      id: cache-packages
      uses: actions/cache@v4
      with:
        path: /var/cache/slackpkg/
        key: slackpkg
    - name: Update and install packages
      run: |
        echo "================================= Updating packages ================================="
        CONF_FILE="/etc/slackpkg/slackpkg.conf"
        sed -i "s/^DIALOG=.*/DIALOG=off/" "$CONF_FILE"
        sed -i "s/^BATCH=.*/BATCH=on/" "$CONF_FILE"
        sed -i "s/^DEFAULT_ANSWER=.*/DEFAULT_ANSWER=y/" "$CONF_FILE"
        sed -i '$s/.*/https:\/\/mirrors\.slackware\.com\/slackware\/slackware64-current\//' /etc/slackpkg/mirrors
        slackpkg update gpg <<< y
        slackpkg update <<< y
        ##############################################
        # slackpkg install ${PACKAGES}
        # slackpkg upgrade-all || true
        # slackpkg upgrade-all || true
        # slackpkg upgrade-all || true
        # slackpkg upgrade-all || true
        ##############################################
        wget https://slackers.it/repository/slackware64-current/gtest/gtest-1.15.2-x86_64-1cf.txz
        ##############################################
        #installpkg *.txz
        #rm *.txz
        #installpkg *.tgz
        #rm *.tgz
    - name: Build
      run: |
        echo "================================= Downloading source code ================================="
        REPO=${GITHUB_REPOSITORY##*/}
        REPO_DIR="/__w/${REPO}/${REPO}"
        mkdir -p ${REPO_DIR}/${NAME}
        cd ./SlackBuilds/$NAME
        wget ${SOURCE}
        sh ${REPO_DIR}/SlackBuilds/${NAME}/${NAME}.SlackBuild
        git config --global --add safe.directory $REPO_DIR
        cp /tmp/*.tgz ${REPO_DIR}/${NAME}
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'updated ${{ env.NAME }}'
        file_pattern: '*.tgz'
