name: Build dragonfly
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    secrets: inherit
    with:
      VERSION: "1.29.0"
      NAME: "dragonfly"
      bobbintb: true
      DOWNLOAD: "https://github.com/dragonflydb/dragonfly/releases/latest/download/dragonfly-x86_64.tar.gz"
      PACKAGES: "ninja boost m4 gettext automake autoconf libtool bobbintb:re2"
