name: Build dragonfly
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    secrets: inherit
    with:
      VERSION: "1.28.1"
      NAME: "dragonfly"
      PACKAGES: "cmake make ninja gc gcc binutils boost kernel-headers m4 automake autoconf guile libtool bison gettext && slackpkg upgrade glibc openssl"
