name: Build dragonfly
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    secrets: inherit
    with:
      VERSION: "1.28.1"
      NAME: "dragonfly"
      GIT: https://github.com/dragonflydb/dragonfly.git
      PACKAGES: "cmake && slackpkg install make && slackpkg install ninja && slackpkg install gc && slackpkg install gcc && slackpkg install binutils && slackpkg install boost && slackpkg install kernel-headers && slackpkg install m4 && slackpkg install automake && slackpkg install autoconf && slackpkg install guile && slackpkg install libtool && slackpkg install bison && slackpkg install gettext && slackpkg upgrade glibc openssl"
