name: -Build go-audit
on:
  workflow_dispatch:
env:
  VERSION: "1.2.0"
  NAME: "go-audit"
jobs:
  slackware-job:
    permissions: write-all
    runs-on: ubuntu-latest
    container:
      image: spaceinvaderone/auto_slack_pack
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        echo "================================= Downloading source code ================================="
        REPO=${GITHUB_REPOSITORY##*/}
        REPO_DIR="/__w/${REPO}/${REPO}"
        ARCHIVE_DIR=${REPO_DIR}/${NAME}/
        mkdir -p ${ARCHIVE_DIR}
        echo "Archive dir"
        echo ${ARCHIVE_DIR}
        cd ${ARCHIVE_DIR}
        wget https://github.com/slackhq/go-audit/releases/download/v${VERSION}/${NAME}-linux-amd64.tar.gz
        tar -xf ${NAME}-linux-amd64.tar.gz ${NAME}
                
        echo "Copying files to temporary folder to archive..."

        dest="./tmp/usr/local/bin/"
        mkdir -p "$dest"
        mv ./${NAME} "$dest"

        dest="./tmp/etc/"
        mkdir -p "$dest"
        wget https://raw.githubusercontent.com/slackhq/go-audit/refs/heads/master/go-audit.yaml.example
        mv ./go-audit.yaml.example "$dest"go-audit.yaml

        dest="./tmp/etc/rc.d/"
        mkdir -p "$dest"
        wget https://raw.githubusercontent.com/slackhq/go-audit/refs/heads/master/contrib/rh-sysv.go-audit.init
        chmod +x rh-sysv.go-audit.init
        mv ./rh-sysv.go-audit.init "$dest"rc.${NAME}
        
        pushd ./tmp
        FILE="${NAME}-v${VERSION}".txz
        makepkg ../${repo}/"${NAME}-v${VERSION}".txz <<< y
        popd
        
        git config --global --add safe.directory $REPO_DIR

        echo "current dir"
        pwd
        echo "find file"
        find / -name *.txz
        # mv ${NAME}-v${VERSION}.txz ${ARCHIVE_DIR}
        echo "ARCHIVE_DIR"
        ls -ls ${ARCHIVE_DIR}
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'updated ${{ env.NAME }}'
        file_pattern: '*.txz'
