name: Build keydb
on:
  workflow_dispatch:
env:
  VERSION: "6.3.4"
  NAME: "keydb"
jobs:
  ubuntu-job:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Update and install packages
      run: |
        echo "================================= Updating packages ================================="
        sudo apt upgrade -y
        sudo apt install -y debhelper libsystemd-dev pkg-config pbuilder build-essential nasm autotools-dev autoconf libjemalloc-dev tcl tcl-dev uuid-dev libcurl4-openssl-dev libbz2-dev libzstd-dev liblz4-dev libsnappy-dev libssl-dev
    - name: Build
      run: |
        echo "================================= Downloading source code ================================="
        git clone --depth 1 --branch v6.3.4 https://github.com/Snapchat/KeyDB.git
        cd KeyDB/
        git submodule init && git submodule update
        wget https://raw.githubusercontent.com/redis/redis/unstable/deps/lua/src/lua_bit.c
        mv lua_bit.c deps/lua/src/lua_bit.c
        #cd pkg/deb/
        #./deb-buildsource.sh
        #cd deb_files_generated/
        #alien -t --scripts *.deb
        cd src/
        rm Makefile
        wget https://raw.githubusercontent.com/Snapchat/KeyDB/main/src/Makefile
        cd ..
        make CFLAGS="-DUSE_PROCESSOR_CLOCK" DEBUG= OPTIMIZATION=-O3\ -flto
    - name: Prepare package
      run: |
        echo "================================= pwd ================================="
        pwd
        bindir=/tmp/${NAME}/usr/bin/
        mkdir -p $bindir
        cd KeyDB/src/
        ls -ls
        mv keydb-server $bindir
        mv keydb-cli $bindir
        mv keydb-benchmark $bindir
        mv keydb-diagnostic-tool $bindir
        docdir=/tmp/${NAME}/usr/doc/${NAME}-${VERSION}/
        mkdir -p $docdir
        mv ../00-RELEASENOTES $docdir
        mv ../BUGS $docdir
        mv ../CONDUCT $docdir
        mv ../COPYING $docdir
        mv ../INSTALL $docdir
        mv ../README.md $docdir
        mv ../TLS.md $docdir
        mkdir -p /tmp/${NAME}/etc/keydb
        mv ../keydb.conf /tmp/${NAME}/etc/keydb
        mv ../sentinel.conf /tmp/${NAME}/etc/keydb
        mkdir -p /tmp/${NAME}/usr/man/man1/
        mv ../pkg/rpm/keydb_build/keydb_rpm/usr/share/man/man1/* /tmp/${NAME}/usr/man/man1/
        mkdir -p /tmp/${NAME}/usr/man/man5/
        mv ../pkg/rpm/keydb_build/keydb_rpm/usr/share/man/man5/* /tmp/${NAME}/usr/man/man5/
        mkdir -p /tmp/${NAME}/install
        cat << EOF > /tmp/${NAME}/install/doinst.sh
        ( cd usr/bin ; rm -rf keydb-sentinel )
        ( cd usr/bin ; ln -sf keydb-server keydb-sentinel )
        ( cd usr/bin ; rm -rf keydb-check-aof )
        ( cd usr/bin ; ln -sf keydb-server keydb-check-aof )
        ( cd usr/bin ; rm -rf keydb-check-rdb )
        ( cd usr/bin ; ln -sf keydb-server keydb-check-rdb )
        EOF
        cat << EOF > /tmp/${NAME}/install/slack-desc
        # HOW TO EDIT THIS FILE:
        # The "handy ruler" below makes it easier to edit a package description. Line
        # up the first '|' above the ':' following the base package name, and the '|' on
        # the right side marks the last column you can put a character in. You must make
        # exactly 11 lines for the formatting to be correct. It's also customary to
        # leave one space after the ':'.
        
             |-----handy-ruler------------------------------------------------------|
        keydb: keydb (A Multithreaded Fork of Redis)
        keydb:
        keydb: KeyDB is a high performance fork of Redis with a focus on
        keydb: multithreading, memory efficiency, and high throughput. In addition
        keydb: to performance improvements, KeyDB offers features such as Active
        keydb: Replication, FLASH Storage and Subkey Expires. KeyDB has a MVCC
        keydb: architecture that allows you to execute queries such as KEYS and
        keydb: SCAN without blocking the database and degrading performance.
        keydb:
        keydb:
        keydb:
        EOF
    - name: Move
      run: |
        echo "================================= Moving artifact ================================="
        REPO=${GITHUB_REPOSITORY##*/}
        REPO_DIR="/home/runner/work/${REPO}/${REPO}"
        mkdir -p ${REPO_DIR}/${NAME}/
        cd /tmp
        tar -cvJf ${NAME}-${VERSION}-x86_64-1loom.txz -C ${NAME}/ .
        cp *.txz ${REPO_DIR}/${NAME}/
        cd $REPO_DIR
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        message: 'updated keydb'
        file_pattern: '*.txz'
