name: Build keydb
on:
  workflow_dispatch:
env:
  VERSION: "6.3.4"
  NAME: "keydb"
jobs:
  ubuntu-job:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Update and install packages
      run: |
        echo "================================= Updating packages ================================="
        sudo apt install -y debhelper libsystemd-dev pkg-config pbuilder build-essential nasm autotools-dev autoconf libjemalloc-dev tcl tcl-dev uuid-dev libcurl4-openssl-dev libbz2-dev libzstd-dev liblz4-dev libsnappy-dev libssl-dev
    - name: Build
      run: |
        echo "================================= Downloading source code ================================="
        git clone --depth 1 --branch v6.3.4 https://github.com/Snapchat/KeyDB.git
        cd KeyDB/
        git submodule init && git submodule update
        wget https://raw.githubusercontent.com/redis/redis/unstable/deps/lua/src/lua_bit.c
        mv lua_bit.c deps/lua/src/lua_bit.c
        make
