name: Build laurel
on:
  workflow_dispatch:
env:
  VERSION: "0.6.3"
  NAME: "laurel"
jobs:
  slackware-job:
    permissions: write-all
    runs-on: ubuntu-latest
    container:
      image: spaceinvaderone/auto_slack_pack
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        echo "================================= Downloading source code ================================="
        REPO=${GITHUB_REPOSITORY##*/}
        REPO_DIR="/__w/${REPO}/${REPO}"
        mkdir -p ${REPO_DIR}/${NAME}
        wget https://github.com/threathunters-io/laurel/releases/download/v0.6.3/laurel-v0.6.3-x86_64-glibc.tar.gz
        tar -xf laurel-v0.6.3-x86_64-glibc.tar.gz
                
        echo "Copying files to temporary folder to archive..."

        dest="../tmp/usr/local/sbin/${NAME}"
        mkdir -p "$dest"
        mv ./${NAME} "$dest"
        
        dest="../tmp/etc/audit/plugins.d/"
        mkdir -p "$dest"
        wget https://raw.githubusercontent.com/threathunters-io/laurel/refs/heads/master/etc/audit/plugins.d/laurel.conf
        mv ./laurel.conf "$dest"
        
        dest="../tmp/etc/laurel"
        mkdir -p "$dest"
        wget https://raw.githubusercontent.com/threathunters-io/laurel/refs/heads/master/etc/laurel/config.toml
        mv ./config.toml "$dest"
        
        pushd ../tmp
        FILE="${NAME}-v${VERSION}".txz
        makepkg ../${repo}/"${NAME}-v${VERSION}".txz <<< y
        popd
        
        find / -name $FILE
        git config --global --add safe.directory $REPO_DIR
        mv /__w/Slackware_Packages/laurel-v0.6.3.txz ${REPO_DIR}/${NAME}
        find / -name *.txz
        pwd
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'updated laurel'
        file_pattern: '*.txz'
