name: Build libbpf
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    secrets: inherit
    with:
      VERSION: "1.6.0"
      NAME: "libbpf"
      SBOPKG: true
      PACKAGES: "make guile gc gcc binutils kernel-headers"
