name: Build node19
on:
  workflow_dispatch:
env:
  VERSION: "19.8.1"
  NAME: "node"
jobs:
  slackware-job:
    permissions: write-all
    runs-on: ubuntu-latest
    container:
      image: spaceinvaderone/auto_slack_pack
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Update and install packages
      run: |
        echo "================================= Updating packages ================================="
        CONF_FILE="/etc/slackpkg/slackpkg.conf"
        sed -i "s/^DIALOG=.*/DIALOG=off/" "$CONF_FILE"
        sed -i "s/^BATCH=.*/BATCH=on/" "$CONF_FILE"
        sed -i "s/^DEFAULT_ANSWER=.*/DEFAULT_ANSWER=y/" "$CONF_FILE"
        sed -i '$s/.*/https:\/\/mirrors\.slackware\.com\/slackware\/slackware64-15.0\//' /etc/slackpkg/mirrors
        slackpkg update <<< y
        slackpkg upgrade-all
    - name: Build
      run: |
        echo "================================= Downloading source code ================================="
        REPO=${GITHUB_REPOSITORY##*/}
        REPO_DIR="/__w/${REPO}/${REPO}"
        mkdir -p ${REPO_DIR}/${NAME}
        wget https://github.com/sbopkg/sbopkg/releases/download/0.38.2/sbopkg-0.38.2-noarch-1_wsr.tgz
        installpkg *.tgz
        rm *.tgz
        sbopkg -r -q
        sbopkg -b ${NAME} <<< p
        git config --global --add safe.directory $REPO_DIR
        cp /tmp/*.tgz ${REPO_DIR}/${NAME}
        cp /tmp/*.txz ${REPO_DIR}/${NAME}
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'updated ${{ env.NAME }}'
        file_pattern: '*.tgz, *.txz'
