name: -Build ply
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    secrets: inherit
    with:
      VERSION: "2.4.0"
      NAME: "ply"
      PACKAGES: autoconf guile automake make m4 flex bison glibc gettext libtool llvm gc gcc binutils
      SOURCE: https://github.com/iovisor/ply.git
