name: Build ply
on:
  workflow_dispatch:
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    with:
      VERSION: "1.5.0"
      NAME: "ply"
