name: Build ply
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-alien-template.yml@main
    secrets: inherit
    with:
      VERSION: "2.4.0"
      NAME: "ply"
      SOURCE: http://archive.ubuntu.com/ubuntu/pool/universe/p/ply-probe/ply_2.4.0-1_amd64.deb
