name: Build redisearch
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    secrets: inherit
    with:
      VERSION: "2.10.12"
      NAME: "redisearch"
      PACKAGES: "make cmake guile gc gcc binutils boost kernel-headers && export BOOST_DIR=/usr/include/boost"
      SOURCE: "https://github.com/RediSearch/RediSearch.git"
