name: Build redis
on:
  workflow_dispatch:
env:
  VERSION: "7.4.0"
  NAME: "redis"
jobs:
  slackware-job:
    permissions: write-all
    runs-on: ubuntu-latest
    container: aclemons/slackrepo
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Update and install packages
      run: |
        echo "================================= Updating packages ================================="
        CONF_FILE="/etc/slackpkg/slackpkg.conf"
        sed -i "s/^DIALOG=.*/DIALOG=off/" "$CONF_FILE"
        sed -i "s/^BATCH=.*/BATCH=on/" "$CONF_FILE"
        sed -i "s/^DEFAULT_ANSWER=.*/DEFAULT_ANSWER=y/" "$CONF_FILE"
        slackpkg update <<< y
        slackpkg install jemalloc

