name: Build redisearch
on:
  workflow_dispatch:
env:
  VERSION: "2.10.7"
  NAME: "redisearch"
jobs:
  ubuntu-job:
    permissions: write-all
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        echo "================================= Downloading source code ================================="
        git clone --branch v2.10.7 https://github.com/RediSearch/RediSearch.git
        #git clone --branch boost-1.86.0 https://github.com/boostorg/boost.git
        cd RediSearch/
        sh ./.install/install_boost.sh 1.86
        git submodule init && git submodule update
        make fetch
        make build
