name: -Build redisearch
on:
  workflow_dispatch:
env:
  VERSION: "2.10.7"
  NAME: "redisearch"
jobs:
  slackware-job:
    permissions: write-all
    runs-on: ubuntu-24.04
    steps:
    - name: Update and install packages
      run: |
        echo "================================= Updating packages ================================="
        sudo apt upgrade -y
        sudo apt install libboost-all-dev -y
        echo "================================= Checkout RediSearch repo ================================="
    - name: Checkout RediSearch repo
      uses: actions/checkout@v4
      with:
        repository: RediSearch/RediSearch
        ref: 'v2.10.7'
        path: RediSearch
    - name: Build
      run: |
        echo "================================= Building RediSearch ================================="
        cd RediSearch/
        git submodule init && git submodule update
        # sed -i 's/RedisModuleEvent_ReplBackup/RedisModuleEvent_ReplAsyncLoad/g' src/notifications.c
        make setup
        make build
        cp /home/runner/work/Slackware_Packages/Slackware_Packages/RediSearch/bin/linux-x64-release/search/redisearch.so /tmp
        cd ..
    - name: Checkout
      uses: actions/checkout@v4
    - name: Move
      run: |
        echo "================================= Moving artifact ================================="
        REPO=${GITHUB_REPOSITORY##*/}
        REPO_DIR="/home/runner/work/${REPO}/${REPO}"
        git config --global --add safe.directory $REPO_DIR
        mkdir -p ${REPO_DIR}/${NAME}/${VERSION}
        mv /tmp/redisearch.so ${REPO_DIR}/${NAME}/${VERSION}
        cd $REPO_DIR
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'updated ${{ env.NAME }}'
        file_pattern: '*.so'
