name: Build bcc
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    secrets: inherit
    with:
      bobbintb: true
      VERSION: "2.10.11"
      NAME: "redisearch"
      PACKAGES: "make guile gc gcc binutils"
      SOURCE: https://github.com/RediSearch/RediSearch.git
