name: Build redisearch
on:
  workflow_dispatch:
env:
  VERSION: "2.10.7"
  NAME: "redisearch"
  
jobs:
  ubuntu-job:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        echo "================================= Downloading source code ================================="
        git clone --branch v2.10.7 https://github.com/RediSearch/RediSearch.git
        cd RediSearch/
        make setup
        make fetch
        make build
