name: Build redisearch
on:
  workflow_dispatch:
env:
  VERSION: "2.10.7"
  NAME: "redisearch"
jobs:
  slackware-job:
    permissions: write-all
    runs-on: ubuntu-latest
    container: aclemons/slackrepo
    steps:
    - name: Cache Docker images.
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: docker-${{ runner.os }}-${{ hashFiles(paths) }}
    - name: Update and install packages
      run: |
        echo "================================= Updating packages ================================="
        CONF_FILE="/etc/slackpkg/slackpkg.conf"
        sed -i "s/^DIALOG=.*/DIALOG=off/" "$CONF_FILE"
        sed -i "s/^BATCH=.*/BATCH=on/" "$CONF_FILE"
        sed -i "s/^DEFAULT_ANSWER=.*/DEFAULT_ANSWER=y/" "$CONF_FILE"
        slackpkg update <<< y
        wget https://slackware.uk/slackware/slackware64-current/slackware64/l/boost-1.86.0-x86_64-1.txz
        upgradepkg boost-1.86.0-x86_64-1.txz
        echo "================================= Checkout RediSearch repo ================================="
    - name: Checkout RediSearch repo
      uses: actions/checkout@v4
      with:
        repository: RediSearch/RediSearch
        ref: 'v2.10.7'
        path: RediSearch
    - name: Build
      run: |
        echo "================================= Building RediSearch ================================="
        cd RediSearch/
        git submodule init && git submodule update
        sed -i 's/RedisModuleEvent_ReplBackup/RedisModuleEvent_ReplAsyncLoad/g' src/notifications.c
        make build
        find / -name redisearch.so
        cd ..
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        echo "================================= Moving artifact ================================="
        ls -ls
        REPO=${GITHUB_REPOSITORY##*/}
        REPO_DIR="/__w/${REPO}/${REPO}"
        git config --global --add safe.directory $REPO_DIR
        mkdir -p ${REPO_DIR}/${NAME}/${VERSION}
        find / -name redisearch.so
        cp ./RediSearch/bin/linux-x64-release/search/redisearch.so ${REPO_DIR}/${NAME}/${VERSION}
        cd $REPO_DIR
        pwd
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        message: 'updated redisearch'
        file_pattern: '*.so'
