name: Build redisearch
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    secrets: inherit
    with:
      VERSION: "2.10.17"
      NAME: "redisearch"
      PACKAGES: "make cmake guile gc gcc binutils kernel-headers"
      GIT: "https://github.com/RediSearch/RediSearch.git"
