name: sbopkg template
on:
  workflow_call:
    inputs:
      NAME:
        description: 'Program name'
        required: true
        type: string
      PACKAGES:
        description: 'Build dependencies to install, space seperated'
        required: false
        type: string
      REINSTALL:
        description: 'Build dependencies to re-install, space seperated'
        required: false
        type: string
      PIP:
        description: 'PIP dependencies to install, space seperated'
        required: false
        type: string
      REPOS:
        description: 'Additional repos to enable, space-separated (e.g. alien-15 conraid-current bobbintb)'
        required: false
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: bobbintb/unraid-cicd-builder
      options: --privileged
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v6
      with:
        clean: true
    -
      name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v7
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
    - 
      name: Cache packages
      id: cache-packages
      uses: actions/cache@v5
      with:
        path: /var/cache/packages
        key: slackware-packages-${{ github.sha }}
        restore-keys: |
          slackware-packages-
    - 
      name: Enable additional repos
      run: | 
        ./add_repos.sh ${{ inputs.REPOS }}
        ls
        cat /etc/slackpkg/slackpkgplus.conf
    - 
      name: Install dependencies
      run: | 
        slackpkg update gpg
        slackpkg update
        slackpkg install ${{ inputs.PACKAGES }}
        slackpkg remove glibc
        slackpkg install glibc
    - 
      name: Build
      run: | 
        sbopkg -r
        sbopkg -b ${{ inputs.NAME }} <<< p
    -
      name: Download existing site
      run: |
        wget -r -np -nH --cut-dirs=1 -P /tmp/pages-artifact \
          https://bobbintb.github.io/Slackware_Packages/builds/ || true
    -
      name: Prepare package folder
      run: |
        rm -rf /tmp/pages-artifact/builds/${{ inputs.NAME }}
        mkdir -p /tmp/pages-artifact/builds/${{ inputs.NAME }}
        find /tmp -maxdepth 1 -name "${{ inputs.NAME }}-*.txz" \
          -exec cp {} /tmp/pages-artifact/builds/${{ inputs.NAME }}/ \;
    -
      name: Generate repo files
      run: |
        cd /tmp/pages-artifact/builds

        echo -e "\e[32mContents of builds:\e[0m"
        ls -ls

        slackpkg update gpg || true
        slackpkg update || true
        slackpkg install slackware64:pinentry slackware64:libsecret slackware64:gtk+2 slackware64:tcl slackware64:expect

        gpg --list-keys
        export REPOSOWNER="${{ github.repository_owner }}"
        export RSS_UUID=$(uuidgen -t)
        export REPOSROOT="/tmp/pages-artifact/builds"

        cat <<EOF > /tmp/script.expect
        #!/usr/bin/expect

        set key [lindex \$argv 0]
        spawn /usr/libexec/slackrepo/gen_repos_files.sh
        expect "Enter ChangeLog.txt description:"
        send "\r"
        expect "Enter your GPG passphrase:"
        send "\$key\r"
        expect eof
        EOF

        chmod +x /usr/libexec/slackrepo/gen_repos_files.sh
        chmod +x /tmp/script.expect
        /tmp/script.expect ${{ secrets.PASSPHRASE }}
    -
      name: Prepare deploy artifact
      run: |
        find /tmp/pages-artifact/builds -mindepth 1 -maxdepth 1 -type d \
          ! -name "${{ inputs.NAME }}" -exec rm -rf {} +
    -
      name: Generate directory listing
      uses: jayanta525/github-pages-directory-listing@v4.0.0
      with:
        FOLDER: ./
    -
      name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    -
      name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
