name: sbopkg template
on:
  workflow_call:
    inputs:
      NAME:
        description: 'Program name'
        required: true
        type: string
      PACKAGES:
        description: 'Build dependencies to install, space seperated'
        required: false
        type: string
      REINSTALL:
        description: 'Build dependencies to re-install, space seperated'
        required: false
        type: string
      PIP:
        description: 'PIP dependencies to install, space seperated'
        required: false
        type: string
      REPOS:
        description: 'Additional repos to enable, space-separated (e.g. alien-15 conraid-current bobbintb)'
        required: false
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: bobbintb/unraid-cicd-builder
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        clean: true

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v7
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}

    - name: Build
      run: | 
        slackpkg update gpg && slackpkg update
        slackpkg install ${{ inputs.PACKAGES }} || true
        sbopkg -r
        sbopkg -b ${{ inputs.NAME }} <<< p

    - name: 1. Download the existing site
      run: |
        mkdir -p /tmp/site-root/builds
        wget -r -np -nH --cut-dirs=2 -P /tmp/site-root/builds \
          --reject "index.html*" \
          https://bobbintb.github.io/Slackware_Packages/builds/ || true

    - name: 2. Remove existing files from package subfolder
      run: |
        rm -rf /tmp/site-root/builds/${{ inputs.NAME }}
        mkdir -p /tmp/site-root/builds/${{ inputs.NAME }}

    - name: 3. Move the package into its subfolder
      run: |
        find /tmp -name "${{ inputs.NAME }}-*.t?z" -exec cp {} /tmp/site-root/builds/${{ inputs.NAME }}/ \;

    - name: 4. Run the gen_repos_files.sh file
      run: |
        # Setup environment for the script
        slackpkg install slackware64:pinentry slackware64:libsecret slackware64:gtk+2 slackware64:tcl slackware64:expect || true
        
        export REPOSOWNER="${{ github.repository_owner }}"
        export RSS_UUID=$(uuidgen -t)
        export REPOSROOT="/tmp/site-root/builds"
        
        cat <<EOF > /tmp/script.expect
        #!/usr/bin/expect
        set key [lindex \$argv 0]
        spawn /usr/libexec/slackrepo/gen_repos_files.sh
        expect "Enter ChangeLog.txt description:"
        send "\r"
        expect "Enter your GPG passphrase:"
        send "\$key\r"
        expect eof
        EOF

        chmod +x /tmp/script.expect
        cd /tmp/site-root/builds
        /tmp/script.expect ${{ secrets.PASSPHRASE }}

    - name: Prepare for Upload
      run: |
        mkdir -p $GITHUB_WORKSPACE/deploy-folder
        cp -a /tmp/site-root/. $GITHUB_WORKSPACE/deploy-folder/

    - name: Generate directory listings
      uses: jayanta525/github-pages-directory-listing@v4.0.0
      with:
        FOLDER: deploy-folder/builds

    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v7
      with:
        path: deploy-folder

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 5. Deploy the page
        id: deployment
        uses: actions/deploy-pages@v4
