name: Build sbotools
on:
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/sbopkg_template.yml@main
    secrets: inherit
    with:
      NAME: "sbotools"
