name: Build slapt-get
on:
  workflow_dispatch:
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    with:
      VERSION: "0.11.10"
      NAME: "slapt-get"
      UPGRADE-ALL: true
      PACKAGES: libidn2 libssh2 libunistring
      SOURCE: "https://github.com/jaos/slapt-get/archive/0.11.10/slapt-get-0.11.10.tar.gz"
