name: Build slapt-get
on:
  workflow_dispatch:
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    with:
      VERSION: "0.11.10"
      NAME: "slapt-get"
      SOURCE: "https://github.com/jaos/slapt-get/archive/refs/tags/0.11.10.tar.gz"
