name: Build SysmonForLinux
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    secrets: inherit
    with:
      VERSION: "1.3.4.0"
      alien-current: true
      NAME: "SysmonForLinux"
      PACKAGES: "make guile gc cmake gcc binutils kernel-headers libxml alien-current:gtest"
      GIT: https://github.com/microsoft/SysmonForLinux.git
