name: Build SysmonForLinux
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    secrets: inherit
    with:
      VERSION: "1.3.4.0"
      alien-15: true
      bobbintb: true
      salix-extra-15: true
      NAME: "SysmonForLinux"
      PACKAGES: "make guile gc cmake gcc binutils kernel-headers alien-15:gtest bobbintb:SysinternalsEBPF salix-extra-15:dotnet-sdk-6 && slackpkg upgrade libxml2"
      GIT: https://github.com/microsoft/SysmonForLinux.git
