name: DEV Build mongodb
on:
  workflow_dispatch:
env:
  VERSION: "7.4.0"
  NAME: "mongodb"
jobs:
  slackware-job:
    permissions: write-all
    runs-on: ubuntu-latest
    container: aclemons/slackrepo
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Update and install packages
      run: |
        echo "================================= Updating packages ================================="
        CONF_FILE="/etc/slackpkg/slackpkg.conf"
        sed -i "s/^DIALOG=.*/DIALOG=off/" "$CONF_FILE"
        sed -i "s/^BATCH=.*/BATCH=on/" "$CONF_FILE"
        sed -i "s/^DEFAULT_ANSWER=.*/DEFAULT_ANSWER=y/" "$CONF_FILE"
        slackpkg update <<< y
        
        
        
    - name: Build
      run: |
        echo "================================= Moving artifact ================================="
        REPO=${GITHUB_REPOSITORY##*/}
        REPO_DIR="/__w/${REPO}/${REPO}"
        mkdir -p ${REPO_DIR}/${NAME}/${VERSION}
        txz_path=$(find / -name *.txz)
        cp ${txz_path} ${REPO_DIR}/${NAME}/${VERSION}
        cd $REPO_DIR
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        message: 'updated redisearch'
        file_pattern: '*.txz'
