name: test-libbpf
on:
  workflow_dispatch:
jobs:
  call-workflow-passing-data:
    permissions:
      contents: write
      actions: write
      issues: write
      pull-requests: write
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    with:
      VERSION: "1.5.0"
      NAME: "libbpf"
      SOURCE: "https://github.com/libbpf/libbpf/archive/refs/tags/v1.5.0.tar.gz"
      PACKAGES: nghttp3
