name: Build valkey
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/sbopkg_template.yml@main
    secrets: inherit
    with:
      NAME: "valkey"
      REPOS: alienbob-15.0 bobbintb
      PACKAGES: "make guile gc gcc kernel-headers binutils pkgconf"
