name: verttest
on:
  workflow_dispatch: # Allow manual trigger workflows
jobs:
  build:
    name: RedisTimeSeries
    runs-on: ubuntu-latest
    steps:
      - id: keydb
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: JohnSully
          repo: KeyDB
          excludes: prerelease, draft
      - id: timeseries
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: RedisTimeSeries/RedisTimeSeries
      - name: Enable additional repos
        run: |
          echo ${{ steps.keydb.outputs.release }}
          echo ${{ steps.timeseries.outputs.release }}
          echo ${{ steps.keydb.outputs.release }}
          echo ${{ steps.timeseries.outputs.release }}

