name: verttest
on:
  workflow_dispatch: # Allow manual trigger workflows
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: my-org/my-tools
      - name: test
        uses: WyriHaximus/github-action-get-previous-tag@v1.4.0
        with:
          fallback: oops
