name: test
on:
  workflow_dispatch: # Allow manual trigger workflows
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Import and Sign
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64
          # gpg --batch --yes --armor --detach-sign bpftool.tar.gz
