name: Workflow template
on:
  workflow_call:
    inputs:
      NAME:
        description: 'Program name'
        required: true
        type: string
      VERSION:
        description: 'Program version'
        required: true
        type: string
      PACKAGES:
        description: 'Build dependencies to install, space seperated'
        required: false
        type: string
      SOURCE:
        description: 'URL of program source archive'
        required: true
        type: string
jobs:
  slackbuild_and_upload:
    runs-on: ubuntu-latest
    container:
      image: spaceinvaderone/auto_slack_pack
      options: --privileged
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cache packages
      id: cache-packages
      uses: actions/cache@v4
      with:
        path: /var/cache/slackpkg/
        key: slackpkg
    - name: Update slackpkg
      if: ${{ inputs.PACKAGES != '' && inputs.PACKAGES != null }}
      run: |
        CONF_FILE="/etc/slackpkg/slackpkg.conf"
        sed -i "s/^DIALOG=.*/DIALOG=off/" "$CONF_FILE"
        sed -i "s/^BATCH=.*/BATCH=on/" "$CONF_FILE"
        sed -i "s/^DEFAULT_ANSWER=.*/DEFAULT_ANSWER=y/" "$CONF_FILE"
        sed -i '$s/.*/https:\/\/mirrors\.slackware\.com\/slackware\/slackware64-current\//' /etc/slackpkg/mirrors
        slackpkg update gpg <<< y
        slackpkg update <<< y
    - name: Install dependencies
      if: ${{ inputs.PACKAGES != '' && inputs.PACKAGES != null }}
      run: slackpkg install ${{ inputs.PACKAGES }}
    - name: Build
      run: |
        echo "================================= Downloading source code ================================="
        REPO=${GITHUB_REPOSITORY##*/}
        REPO_DIR="/__w/${REPO}/${REPO}"
        mkdir -p ${REPO_DIR}/${{ inputs.NAME }}
        cd ./SlackBuilds/${{ inputs.NAME }}
        wget ${{ inputs.SOURCE }}
        # sh ${REPO_DIR}/SlackBuilds/${{ inputs.NAME }}/${{ inputs.NAME }}.SlackBuild
        output=$(sh ${REPO_DIR}/SlackBuilds/${{ inputs.NAME }}/${{ inputs.NAME }}.SlackBuild)
        package_path=$(echo "$output" | grep -oP '(?<=package )/.*(?= created)')
        echo "package_path=${package_path}" >> $GITHUB_ENV
    - name: Upload
      env:
        PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
      run: |
        curl -X POST https://api.buildkite.com/v2/packages/organizations/bobbintb/registries/slackware/packages \
        -H 'Authorization: Bearer "$PACKAGECLOUD_TOKEN"' \
        -F "file=@${package_path}"
