name: Build yq
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    secrets: inherit
    with:
      VERSION: "4.45.1"
      NAME: "yq"
      alien-15: true
      PACKAGES: "alien-15:google-go-lang"
      SBOPKG: true
