name: Build yq
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    secrets: inherit
    with:
      LATEST_VERSION: true
      alien-15: true
      NAME: "yq"
      PACKAGES: "alien-15:google-go-lang && echo 'PATH=$(ls -d /usr/lib64/go[0-9]*.[0-9]*.[0-9]* 2>/dev/null | sort -V | tail -n1)/bin:$PATH' >> $GITHUB_ENV"
      SBOPKG: true
