name: Build yq
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  make_slackware_package:
    uses: bobbintb/Slackware_Packages/.github/workflows/workflow-template.yml@main
    secrets: inherit
    with:
      LATEST_VERSION: true
      NAME: "yq"
      PACKAGES: "google-go-lang"
      SBOPKG: true
